### ISSUE TITLE
Re-fires at a position

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#11]
As an _attacker_

I want to _notified is i re-attack a position_

So that I don't _lose my turn_

**Additional Details**

Assumptions :-

       1. The game has been started.

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _my turn to attack_
  - When _I re-attack at a  position_
  - Then _I should be warned with a message_
- [ ] Criteria 2
  - Given _my turn to attack_
  - When _I re-attack at a  position_
  - Then _my turn should not be changed_

**Comment by tejam897** [comment]
Mark acceptance criteria as done before closing it.
