### ISSUE TITLE
Fired shot is miss

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#12]
As a _attacker_

I want to _know details of miss_

So that I may _plan my strategy_

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _a running game and your turn_
  - When _I have missed a shot_
  - Then _i should know the details of miss_

**Comment by tejam897** [comment]
This story has been merged with fired shot is a hit or miss.
