### ISSUE TITLE
Got hit

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#14]
As a _player_

I want to _know where my opponent has hit_

So that I _can know my fleet status_

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _a running game and opponent shot was hit_
  - When _opponent hits on my ship_
  - Then _the damaged position should be highlighted with red_

**Comment by tejam897** [comment]
It has been merged with fired shot is a hit.
