### ISSUE TITLE
Escapes hit

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#15]
As a _player_

I want to _that my opponent misfired_

So that I  _know my ships are safe_

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _a running game and opponents turn_
  - When _my opponent misfires_
  - Then _the missed position should be hi lighted with miss _
- [ ] Criteria 2
  - Given _a running game and opponents turn_
  - When _opponent misfires_
  - Then _my number of escapes should be updated_

**Comment by tejam897** [comment]
This story has been merged with fired shot is a hit or miss.
