### ISSUE TITLE
Player lost

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#17]
As a _player_

I want to _know whether my fleet has been destroyed_

So that I _know I have lost_

**Additional Details**

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _a running game, opponents turn_
  - When _opponents shot was a hit and all my ships sunk_
  - Then _I should know all my ships are sunk_
- [ ] Criteria 2
  - Given _a running game, opponents turn_
  - When _my fleet is destroyed_
  - Then _I should see a defeat message_
- [ ] Criteria 3
  - Given _a running game, opponents turn_
  - When _I am lost_
  - Then _I should see a play again option_

**Comment by tejam897** [comment]
It has been merged as player wins or loses.
