### ISSUE TITLE
Player 1 is waiting

### ISSUE THREAD

**Issue by tejam897** [STEP-tw/battleship-phoenix#19]
As a _first player_

I want to _to see waiting message_

So that I know _my opponent has not joined the game_

**Additional Details**

Assumptions :-

      1. Game has been created.
 
      2. First player has joined.

      3. opponent hasn't joined. 
     
**Acceptance Criteria**

- [x] Criteria 1
  - Given _a created game_
  - When _i'm waiting for opponent_
  - Then _i should see a waiting message_

**Comment by sridevs** [comment]
[#19] kindly integrate it with create game [#6].
