### ISSUE TITLE
Views message box

### ISSUE THREAD

**Issue by tejam897** [STEP-tw/battleship-phoenix#30]
As a _player_

I want to _see a message box_

So that I can _see game related messages_

**Additional Details**

Use this section if you have any additional things to say that don't fit the _As a ..., I want to ..._ format

**Acceptance Criteria**

- [x] Criteria 1
  - Given _game page with battleship title on top_
  - When i _look just below heading_
  - Then _i should see a message box_

**Comment by sridevs** [comment]
[#30] 
make it visible
