### ISSUE TITLE
Views about us

### ISSUE THREAD

**Issue by ruwik** [STEP-tw/battleship-phoenix#35]
As a _player_

I want to _know about developers team_

So that I may _know more about them_

**Additional Details**

     User has landed on home page.
     About us option should be below settings.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _about us option_
  - When _I click on about us_
  - Then _I should see the details about developers_

**Comment by niteshrj** [comment]
BA's are not allowed to sign up for the story and work on it.
