### ISSUE TITLE
bug in the story join game 

### ISSUE THREAD

**Issue by QanjuQ** [STEP-tw/battleship-phoenix#42]
BUG 
  when you try to join the game though there are two players already in game 
then your set a cookie

**Additional Details**
Story details in which we have the bug
   Story No.  :   9
   Story  Title : Join  a game

![screen shot 2018-02-22 at 12 07 56 pm](https://user-images.githubusercontent.com/34647152/36524596-843c19f8-17cc-11e8-8654-4efd2d27a7a6.png)

![screen shot 2018-02-22 at 12 11 05 pm](https://user-images.githubusercontent.com/34647152/36524665-d043a230-17cc-11e8-923a-017041e143ed.png]

actual  behavior : when try to join game,
 and game has two players,
 sets a cookie. 

expected behavior : when i try to join game,
and game has two players,
 1. it should not set a cookie 
 2. inform that i can't join
 3. should not add me as player.

**Comment by sridevs** [comment]
This issue got resolved when multiple games was introduced. So I'm closing it.
