### ISSUE TITLE
Multiple games

### ISSUE THREAD

**Issue by niteshrj** [STEP-tw/battleship-phoenix#48]
As a _Player_

I want to _create a new game if there is already a game with two players running_

So that _I can create my own game even if other games are running._

**Assumptions** 

There is already a play now option with host or join.
Player can host or join a game.

**Acceptance Criteria**

- [ ] Criteria 1
  - Given _there is already a game with two players playing_
  - When _i click host_
  - Then _i should be able to create a new game_
- [ ] Criteria 2
  - Given _there is already a game with one player waiting_
  - When _i click host_
  - Then _i should be able to create a new game_
- [ ] Criteria 3
  - Given _there is already a game with two players and a game with one host_
  - When _i click join_
  - Then _i should be able to join that game_

**Comment by sridevs** [comment]
[#48] we sridev and teja worked on this story. If you are really interested in picking up this story, kindly discuss with us.
