### ISSUE TITLE
Host button shouldn't be enabled after hosting a game

### ISSUE THREAD

**Issue by niteshrj** [STEP-tw/battleship-phoenix#54]
**Bug** - when i click play now, a pop up appears with the option to host the game but i neither host the game nor close the pop up and hit the localhost from another incognito window and host the game. now i can return to the previous window and host the same game.
**Requirement** - After hosting a game the host option should not be there, only join option should be there.

**Comment by sridevs** [comment]
This issue has been taken care in multiple games feature. Now  multiple games can be hosted and players can join any game as per their wish, so I am closing this issue.
