### ISSUE TITLE
highlighting sunk ship on enemy's base

### ISSUE THREAD

**Issue by dhanasp** [STEP-tw/battleship-phoenix#63]
As a _player_

I want to _see my enemy's ships that I have made sunk_

So that I _can know whether a ship sunk or not_

**Acceptance Criteria**

- [x] Criteria 1
  - Given _enemy's base_
  - When _player hit on it and one whole ship is sunk_
  - Then _that ship should be highlighted_

**Comment by rathorarv** [comment]
last sunk is not highlighting.
