### ISSUE TITLE
leave game option while game is running

### ISSUE THREAD

**Issue by dhanasp** [STEP-tw/battleship-phoenix#65]
As a _player_

I should _have the leave game option while game is running_

So that  _given any time I can leave the game_

Notes:-
1.We have a working game where multiple games can run simultaneously.
2.Leave game option should be made available during setup phase, when player has 
   positioned his ships and is waiting for his opponent.

**Acceptance Criteria**

- [x] Criteria 1
  - Given _running game_
  - When _I click on leave game_
  - Then _I should be asked "do I really want to leave the game"_

- [x] Criteria 2
  - Given _I have clicked leave game_
  - When _I  confirm that I leave_
  - Then _I should have left the game_

- [x] Criteria 3
  - Given _my opponent has left the game_
  - When _I complete my turn_
  - Then _I should know my opponent has left and I should be declared as winner_

**Comment by rathorarv** [comment]
After game over i should not able to quit game and quit url should be forbidden if there is no game.

**Comment by singhIshu** [comment]
Acceptance criteria is not clear.
     1.Whether the quit button is displayed on turn basis.
     2.Whether the opponent is declared winner.

**Comment by sridevs** [comment]
You should also give the quit option during setup phase, when player is waiting for his opponent.
