### ISSUE TITLE
security issue: player can announce ready by manipulating code through console.

### ISSUE THREAD

**Issue by sridevs** [STEP-tw/battleship-phoenix#80]
Actual: I can announce ready even without placing ships by changing the response.status to true in check fleet status function.

Expected: Block such hacks by proper validation.

**Acceptance Criteria**
Assumption:
I have changed the some source code in front end to make this happen.

- [x] Criteria 1
  - Given _I haven't placed my ship and_
  - When _I click ready_
  - Then _I should be asked to place all the my ships _
- [x] Criteria 2
  - Given _I haven't placed my ship and_
  - When _I click ready_
  - Then _the game should not start _ #46

**Comment by dhanasp** [comment]
for now, the game doesn't start but it hangs on setup state. when the opponent gets a leave game option he can quit the game, so this issue will be resolved when he gets leave game option has been implemented.
