### ISSUE TITLE
Option to place ships at random positions.

### ISSUE THREAD

**Issue by rathorarv** [STEP-tw/battleship-phoenix#82]
As a _player_

I want to _place all my ships in single shot_

So that I may _place all my ships randomly and quickly on the ocean grid_

**Acceptance Criteria**

- [x] Criteria 1
  - Given _I am on game page and I have to place all my ships to play game_
  - When _I click on auto place button_
  - Then _all my ships should be placed at random positions on the ocean grid_
- [x] Criteria 2
  - Given _I am on game page and I have already placed all my ships to play game_
  - When _I click on auto place button again_
  - Then _all my ships should be placed at some different random position on the ocean grid_

**Comment by sridevs** [comment]
There is a security issue in [#81]validating ship positions. We expect it to be resolved, as our story depends on that issue. So we are moving it back to ready for dev.
